### ISSUE TITLE
7tv package

### ISSUE THREAD

**Issue by Functioneel** [alazymeme/chocolatey-packages#5]
would it be possible to make a 7tv package? :)

**Comment by ALazyMeme** [comment]
> would it be possible to make a 7tv package? :)

Once complete, 7tv will be merged into master. I don't want to waste effort making a 7tv package if it'll be merged in a few weeks time anyway: https://github.com/Chatterino/chatterino2/pull/3071

**Comment by zneix** [comment]
Also see seventv/chatterino7#18

**Comment by ALazyMeme** [comment]
https://community.chocolatey.org/packages/chatterino7
Pending approval
